spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrumio_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate

  jackson:
    property-naming-strategy: SNAKE_CASE

  application:
    name: scrumio

