spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  flyway:
    enabled: true
    locations: classpath:db/migrations

  application:
    name: scrumio

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

auth-service:
  url: ${AUTH_SERVICE_URL}

