version: '3.8'

services:

  frontend:
    image: ghcr.io/ysayonnar/scrumio-frontend:latest
    build: ../frontend/
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      PORT: 80
      BACKEND_URL: ${BACKEND_URL}
      AUTH_SERVICE_URL: ${FRONTEND_AUTH_SERVICE_URL}
    depends_on:
      backend:
        condition: service_healthy
      auth-service:
        condition: service_started

  backend:
    image: ghcr.io/ysayonnar/scrumio-backend:latest
    build: ../
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:${DB_PORT}/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AUTH_SERVICE_URL: http://auth-service:80
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8080' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-service:
    image: ghcr.io/ysayonnar/scrumio-auth-service:latest
    build: ../go-auth-service/
    restart: always
    ports:
      - "${AUTH_SERVICE_PORT}:80"
    environment:
      ENV: dev
      HOST: 0.0.0.0
      PORT: 80
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL_MODE: disable
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_DURATION: 15m
      JWT_REFRESH_DURATION: 168h
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: scrumio-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    restart: always
    container_name: scrumio-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_data:
  redis_data:
