version: '3.8'

services:

  frontend:
    build: ../frontend/
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      backend:
        condition: service_healthy
      auth-service:
        condition: service_started

  backend:
    build: ../
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:${DB_PORT}/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AUTH_SERVICE_URL: http://auth-service:80
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8080' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-service:
    build: ../go-auth-service/
    restart: always
    ports:
      - "${AUTH_SERVICE_PORT}:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: scrumio-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    restart: always
    container_name: scrumio-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_data:
  redis_data:
